### ISSUE TITLE
[unknown version] Error: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by CraigLindsey** [jssimporter/JSSImporter#140]
Hi All,

When running some recipes both from AutPkgr and manually from the command line, the runs fails with the error:

`The following recipes failed:
    /Users/clindsey/Library/AutoPkg/RecipeOverides/Adobe Flash PlayerStarzOvweride.jss.recipe
        Error in local.jss.Adobe Flash PlayerStarzOvweride: Processor: JSSImporter: Error: execv() arg 2 must contain only strings`

`The following packages were copied:
    Pkg Path                                                                                                           
    --------                                                                                                           
    /Users/clindsey/Library/AutoPkg/Cache/local.jss.Adobe Flash PlayerStarzOvweride/Adobe Flash Player-30.0.0.134.pkg  
`

I've googled and read the issues pages and posted questions on the Mac Admins Slack and so far, no one seems to be familiar with this error.

Anyone here seen it before?

Config: AutpPkg 1.0.4:Git 2.15.2:JSS Importer 1.0.4:Munki Tools 3.3.1.3573:Python 2.7.15:macOS 10.13.5

Thanks for having a look!

**Comment by grahampugh** [comment]
Hi @CraigLindsey is the recipe available to view on the web somewhere? I'm going to guess there is a typo in the override but would have to have a look.
