### ISSUE TITLE
[1.0.1b3] Package uploaded even if it already exists in CDP (S3)

### ISSUE THREAD

**Issue by golbiga** [jssimporter/JSSImporter#141]
Installed 1.0.1b3 the other day and it resolved ssl issues that I was seeing, but I'm noticing that packages are uploaded every single time, even if they already exist in the bucket.  

See below:
JSSImporter: JSSImporter version: 1.0.1.
GET https://server.com:8443/JSSResource/jssuser: Success.
Retrieving data from JSS...
GET https://server.com:8443/JSSResource/jssuser: Success.
JSSImporter: JSS version: '10.5.0-t1527689731'
GET https://server.com:8443/JSSResource/categories/name/Developer%20Tools: Success.
JSSImporter: Category type: category-'Developer Tools' already exists according to JSS, moving on...
GET https://server.com:8443/JSSResource/packages/name/Atom-1.28.2.pkg: Success.
JSSImporter: Pkg-object already exists according to JSS, moving on...
PUT https://server.com:8443/JSSResource/packages/id/481: Success.
Retrieving data from JSS...
GET https://server.com:8443/JSSResource/packages/id/481: Success.
JSSImporter: Package reboot_required updated.
PUT https://server.com:8443/JSSResource/packages/id/481: Success.
Retrieving data from JSS...
GET https://server.com:8443/JSSResource/packages/id/481: Success.
JSSImporter: Package boot_volume_required updated.
JSSImporter: Copying Atom-1.28.2.pkg to all distribution points.
JSSImporter: Copying to https://server.com:8443
<jss.curl_adapter.CurlResponseAdapter object at 0x113911510>
JSSImporter: Copied Atom-1.28.2.pkg

**Comment by elvisizer** [comment]
same here, also using S3.
combining this issue with the increase in invalid checksums generated for the uploads has made jss-importer pretty dangerous to use right now!

**Comment by grahampugh** [comment]
@golbiga @elvisizer Can either of you confirm whether this behaviour is corrected in 1.0.2b3? Especially in light of the `STOP_IF_NO_JSS_UPLOAD` default.

**Comment by grahampugh** [comment]
No response since June so closing. Reopen if the issue persists in 1.0.5.
