### ISSUE TITLE
SSO - Anyway to use JSS Import but keep SSO on other accounts

### ISSUE THREAD

**Issue by master-vodawagner** [jssimporter/JSSImporter#143]
Hi,

My organization needs to keep SSO enabled for Jamf Pro Accounts and needs to be the main method to login.

Is there anyway to use the failover URL to authenticate with my API account used for JSS Import?

**Comment by robison-scott** [comment]
We use okta. I just created an apiuser account locally on JAMF and put in the jss url without the failover portion. Works ok.

**Comment by master-vodawagner** [comment]
Any chance you can create some steps?

Because I've done exactly what you have said but we get the Microsoft SAML page

**Comment by robison-scott** [comment]
For the APIUser, go to Settings->System Settings->Jamf Pro User Accounts & Groups->New->Standard User Account. Give it the appropriate rights. I've installed autopkgr so you can see what my settings look like (attached). The only thing to note is that it you'll get that prompt that tries to direct you somewhere else. Just ignore it and keep your JSS URL. 

![autopkgrsetting](https://user-images.githubusercontent.com/15644836/51488546-0edf6500-1d63-11e9-8267-c24f51fbdaf0.jpg)

Also that, the biggest problem for me setting this up was the older version of OpenSSL installed on the computer or the POS libre suite on Mojave. I couldn't establish a connection at all. Luckily, I found this and it fixed my issues: https://comeroutewithme.com/2016/03/13/python-osx-openssl-issue/

**Comment by master-vodawagner** [comment]
Hmm still not working, what options have you checked in Jamf Settings > System Settings > Single Sign On under the Single Sign-On (SSO) Utilization section only

**Comment by fishd72** [comment]
You shouldn't need to worry about those settings as you need to use a **local** Jamf account (not LDAP / SSO whatever) to login, so the SSO settings don't apply. I've the exact same setup as @robison-scott above and it works fine with Autopkg.

**Comment by grahampugh** [comment]
@master-vodawagner I believe this issue is solved by the comments offered by @fishd72 and @robison-scott
