### ISSUE TITLE
[1.0.1b3] Overly verbose output to Slack from AutoPkgr

### ISSUE THREAD

**Issue by zacharysfisher** [jssimporter/JSSImporter#144]
When using the above version of JSSImporter it uploads great to my Local and CDP.  However, the logs that Autopkg and Autopkgr sends to the slack channel includes every API call and Curl command being sent.  Is there a way to clean up the output so it's more human readable?

**Comment by grahampugh** [comment]
Version 1.0.2 reverts to using requests, which removes this behaviour.
