### ISSUE TITLE
Error Mounting Url

### ISSUE THREAD

**Issue by ktaylor25** [jssimporter/JSSImporter#170]
Hello,

I recently moved my distribution point to a new Windows server. Ever since, when I run my AUTOPKG recipes, I get this error: "Error mounting url "smb://DP/path/here/: none"

I've checked my read/write accounts multiple times.. they work. I can mount the share manually no problem.

If I open a Finder window and watch while running the recipes, the share does actually mount. But still I get the error message and the recipe does not complete.

The only thing I can think of is that the new DP is not located at the root of the server.. it is buried one directory down, whereas that was not the case before. Does this make a difference (assuming DP settings are entered correctly)?
![67795783-d173da80-fa4c-11e9-9769-da8b3b536983](https://user-images.githubusercontent.com/57151016/68310153-2202bd80-0075-11ea-8c31-3603abc4ca60.png)
![67795779-cfaa1700-fa4c-11e9-9a16-aadcc436fbcf](https://user-images.githubusercontent.com/57151016/68310160-24651780-0075-11ea-9d51-17ef2be4a52b.png)

I've attached a screen shot of my JSSImporter settings as well as the error message. Any guidance is appreciated

**Comment by grahampugh** [comment]
I'm not sure if it can handle sub-folders of mount points. Is there any reason why you don't create a mount point directly at `smb://consus.XXX.local:139/CasperShare`?

**Comment by ktaylor25** [comment]
I thought that may be the problem.  I requested that infrastructure make that change. Unfortunately I do not have account access to make that change myself, so I am waiting.

Thanks for the response. I will post a followup once I have a solution.

**Comment by grahampugh** [comment]
Hi @ktaylor25 just to be clear, I don't know if that is the problem or not but it would need to be tested. Certainly it looks like the only change you made, so that would be my guess. But I don't have a mechanism to test it right now.

**Comment by ktaylor25** [comment]
This is now solved.  The issue was indeed related to the CasperShare directory _not_ being at the root of the volume. We moved it there, updated my settings, and everything works perfectly once again.

Thanks!
