### ISSUE TITLE
Jamf Connect Recipes Failures

### ISSUE THREAD

**Issue by zacharysfisher** [jssimporter/JSSImporter#171]
This started today with new releases of connect getting errors below

`CodeSignatureVerifier: hdiutil imageinfo error nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
nx_kernel_mount:1473: : checkpoint search: largest xid 4, best xid 4 @ 7
 with image /Users/USER/Library/AutoPkg/Cache/local.jss.JamfConnectSync.swl/downloads/Jamf Connect Sync.dmg.
/Users/USER/Library/AutoPkg/Cache/local.jss.JamfConnectSync.swl/downloads/Jamf Connect Sync.dmg is not mounted
`

Attempted to update JSSImporter and update the repos with same result.  Any thoughts?

**Comment by grahampugh** [comment]
@zacharysfisher Is this specific to the Jamf Connect recipe? If so it's not a product issue with JSSImporter. Please try asking for help in Slack, e.g. #AutoPkg channel.
