### ISSUE TITLE
[1.0.5] STOP_IF_NO_JSS_UPLOAD functionality

### ISSUE THREAD

**Issue by qu1gl3s** [jssimporter/JSSImporter#177]
I'll first start off that this may be considered a feature request and not a bug so judge this as you will.

I'm currently having an issue where occasionally packages do not attach to policies after running the recipe. Running the recipe again resolves the issue. It's intermittent and difficult to diagnose.

A suggestion by @shawnhonsberger on the #jss-importer channel suggested I turn on the STOP_IF_NO_JSS_UPLOAD that I had turned off for the actual reason I'm lodging for below.

_This may very well be an issue with the way I've set up my AutoPkg environment so if this isn't possible to fix, please let me know and when the move to JSSImporter 2 happens, I'll make changes as necessary._

I have two recipes for a piece of software, an example, Zoom.

Zoom has an installation recipe and an update recipe. These are then two separate policies in Jamf Pro. 

The issue that's occurring is if a new version of a piece of software comes out, the installation recipe will download, package and upload as normal and update the policy. The update recipe will then go through the same process and soft fail because the package already exists. The recipe then quits and moves on. 

What I'd expect is the JSS Importer would then continue the process of making the normal API calls it would to overwrite the policy referencing the package but this doesn't occur, the issue that then happens is the installation recipe is up to date and the update recipe isn't.

I'm essentially asking for the ability for JSS Importer to skip the package upload part as normal, this is a good feature but still complete the API call to Jamf Pro to overwrite the policy.

If this was written in this way, I'd assume my first issue above would disappear when I would then leave the STOP_IF_NO_JSS_UPLOAD set as default.

Happy to have a chat about this outside of Github if need be. I'm rquigley on the MacAdmins Slack.

**Comment by grahampugh** [comment]
I don't believe a fix is necessary here. You should add the key `STOP_IF_NO_JSS_UPLOAD=False` specifically to your second recipe. 

Or, you could put both JSSImporter processes in a single recipe, or have the installation recipe as the parent of the update recipe.
