### ISSUE TITLE
JSSImporter Single Override Multipe Policy Templates

### ISSUE THREAD

**Issue by albiii** [jssimporter/JSSImporter#181]
I am trying to have one recipe override create two policies in my JSS. Syntax is below.

![Screen Shot 2020-06-10 at 3 53 00 PM](https://user-images.githubusercontent.com/5394467/84326735-84073200-ab32-11ea-8461-975fe202c605.png)

**Comment by grahampugh** [comment]
Sorry, that's all wrong. Don't put processors in an override. Make your own JSS recipe with two processors in it. Here's an example: https://github.com/autopkg/grahampugh-recipes/blob/master/_JSS_Production_Recipes/ProdSelfService.jss-prod.recipe
