### ISSUE TITLE
Big Sur smbfs mount issues

### ISSUE THREAD

**Issue by greatkemo** [jssimporter/JSSImporter#187]
Hi Folks,

After upgrading an AutoPKG Mac Mini I am using for testing to Big Sur, I am getting lots of errors with the JSSImporter.

It seems that /Volumes does not handle the mount point as it used to with Catalina and earlier.  Without creating the jamfshare directory first under /Volumes and setting the permissions, it would not mount smbfs even if you manually did it.

Also as /Volumes now seems to require the user to have elevated privileges, could we update disrtibution_points.py to instead create /Users/Shared/"share_name" if it does not exist then mount to it?

Happy to provide more information if required.

Best regards,
Kamal

**Comment by novaksam** [comment]
I have the same issues with AFP mounting. I tried pre-creating the folders in /Volumes, but they disappeared after dismounting, so I modified distribution_points.py like you suggested, but I needed to pre-create the folders there, so I opted to modify distribution_point.py to create the folders on Mac OS.

**Comment by grahampugh** [comment]
Hi all, please can you test the package I just uploaded in the v1.1.4 pre-release? This changes the mount point to `/Users/Shared` which solved the problem in my tests. You'll want to consider any consequences of this change. Note that the folder `/Users/Shared/(MOUNTPOINT)` is unmounted but not deleted. Does this matter to you?
