### ISSUE TITLE
/Users/Shared instead of /Volumes ?!

### ISSUE THREAD

**Issue by aduffner** [jssimporter/JSSImporter#192]
Hello all,

it seems that JSSImporter is using a wrong path to mount. Of course we use the current version (1.1.5).
Here is what we get, when we try to run our recipe with JSSImporter as Processor:
```
PathDeleter: Deleted /Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/payload
PathDeleter: Deleted /Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/unpack
PathDeleter: Deleted /Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/Scripts
JSSImporter
mount_smbfs: URL parsing failed, please correct the URL and try again: Invalid argument
mount: /Users/Shared/dp$ failed with 64
Command '['mount', '-t', 'smbfs', '//EMEA\\user:pass@server.net:445/dp$', '/Users/Shared/dp$']' returned non-zero exit status 64.
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/receipts/CitrixWorkspace.jss-receipt-20210811-102227.plist
 
The following recipes failed:
CitrixWorkspace.jss.corporation
Error in local.corporation.jss.CitrixWorkspace: Processor: JSSImporter: Error: Command '['mount', '-t', 'smbfs', '//EMEA\\user:pass@server.net:445/dp$', '/Users/Shared/dp$']' returned non-zero exit status 64.
 
The following new items were downloaded:
Download Path 
------------- 
/Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/downloads/Citrix Workspace.dmg 
 
The following packages were copied:
Pkg Path 
-------- 
/Users/admin/Library/AutoPkg/Cache/local.corporation.jss.CitrixWorkspace/Scripts/Install Citrix Workspace.pkg
```

After we changed the path in line 145 of `distribution-points.py` from `/Users/Shared` to `/Volumes` it works again.
-> https://github.com/jssimporter/python-jss/blob/master/jss/distribution_points.py

I am curious about your feedback, thank you in advance.

**Comment by grahampugh** [comment]
The path was changed because mounts to /Volumes stopped working on Big Sur. See https://github.com/jssimporter/python-jss/blob/master/CHANGELOG.md

I wonder if the fact that your share name has a dollar in it is significant?

**Comment by aduffner** [comment]
@grahampugh Thanks for the link! Was looking for something similar in the JSSImporter changelog. 

The $ in the name is just for a hidden share, but that shouldn't matter according to the changelog since it's listed as a safe character. 

That the behavior comes from the macOS version confuses me, since we have Big Sur installed on the computer (still 11.2.3) and we mount successfully under `/Volumes`.
