### ISSUE TITLE
Multiple JSSIMPORTER in one receipe

### ISSUE THREAD

**Issue by iannels** [jssimporter/JSSImporter#194]
I am experencing an issue when attepmting to add 2 JSSIMPORTER processors to one receipe. I have faoolowed the process of adding it to my recipe override, but when ran, it will ignore the additional process and only run what is in the input. Is there any working examples out there to help guide me?

I apologize if this is not the correct format to ask for this.

**Comment by grahampugh** [comment]
@iannels MacAdmins Slack #jss-importer Chanel would be a better forum. Let me know if you don't know what this is.
